### ISSUE TITLE
open where is  datasource json sample of topo panel plugin? 

### ISSUE THREAD

**Issue by gaohongfeng1977** [deepflowio/deepflow-gui-grafana#108]
deepflow 老师，你好！

我搜遍了这个项目目录，没有找到 topo plugin的数据源 的json格式，能否回复一下json数据样列，谢谢啦

**Comment by twou12031** [comment]
<img width="2173" alt="image" src="https://github.com/deepflowio/deepflow-gui-grafana/assets/30427789/cf2cf24b-b4f9-483f-b17a-298d6217d691">

以上面的图作为说明:
- `frames.data` 是实际的数据
- `frames.schema` 是对数据的描述

Topo Panel 的特殊要求: 
`frames.schema.meta.custom` 中, 增加了一些绘制的必要信息
  - `returnTags`: 数据中哪些字段是 `Tags`
  - `returnMetrics`: 数据中哪些字段是 `Metrics`, 这些字段需要在 topo 图中, 两个节点之间的连线上显示
    - `unit`: `Metrics` 的初始单位, 如果用户没有在 `panel options` 中改写单位, 则显示此单位
  - `from`: 用户在 `DeepFlow datasource` editor `GROUP BY` 中选择的 客户端的 Tag
    - 均参与数据二次聚合
  - `to`: 用户在 `DeepFlow datasource` editor `GROUP BY` 中选择的 服务端的 Tag
    - 均参与数据二次聚合
  - `common`: 用户在 `DeepFlow datasource` editor `GROUP BY` 中选择的 不区分端的 Tag
    - 除 `observation_point `, `Enum(observation_point)` 外, 参与数据二次聚合

获取到的数据后的处理
  1. 通过 `from`, `to`, `common` 中参与数据二次聚合的 tags 信息, 对数据做二次聚合, 获取 topo 中的 每一根 link
    - 主要是排除 `observation_point `, `Enum(observation_point)` 对聚合的影响, 如果不处理会导致 node 过多
  2. 根据上面处理后的 links 数据, 生成 nodes 数据
    -  通过 `from` + `common` 和 `to` + `common` 生成 id, 一致的视为同一个 node
    
 数据处理完成之后, 调用 `deepflow-vis-js` 进行绘制

**Comment by gaohongfeng1977** [comment]
感谢老师的回复，太赞了，非常有帮助，学习到了！
